from enum import Enum
class Language(int, Enum):
    ab = 1 # Abkhazian
    aa = 2 # Afar
    af = 3 # Afrikaans
    ak = 4 # Akan
    sq = 5 # Albanian
    am = 6 # Amharic
    ar = 7 # Arabic
    an = 8 # Aragonese
    hy = 9 # Armenian
    av = 11 # Avaric
    ae = 12 # Avestan
    ay = 13 # Aymara
    az = 14 # Azerbaijani
    bm = 15 # Bambara
    ba = 16 # Bashkir
    eu = 17 # Basque
    be = 18 # Belarusian
    bn = 19 # Bengali
    bi = 20 # Bislama
    bs = 21 # Bosnian
    br = 22 # Breton
    bg = 23 # Bulgarian
    my = 24 # Burmese
    ca = 25 # Catalan, Valencian
    ch = 26 # Chamorro
    ce = 27 # Chechen
    ny = 28 # Chichewa, Chewa, Nyanja
    zh = 29 # Chinese
    cu = 30 # Church Slavonic, Old Slavonic, Old Church Slavonic
    cv = 31 # Chuvash
    kw = 32 # Cornish
    co = 33 # Corsican
    cr = 34 # Cree
    hr = 35 # Croatian
    cs = 36 # Czech
    da = 37 # Danish
    dv = 38 # Divehi, Dhivehi, Maldivian
    nl = 39 # Dutch, Flemish
    dz = 40 # Dzongkha
    en = 41 # English
    eo = 42 # Esperanto
    et = 43 # Estonian
    ee = 44 # Ewe
    fo = 45 # Faroese
    fj = 46 # Fijian
    fi = 47 # Finnish
    fr = 48 # French
    fy = 49 # Western Frisian
    ff = 50 # Fulah
    gd = 51 # Gaelic, Scottish Gaelic
    gl = 52 # Galician
    lg = 53 # Ganda
    ka = 54 # Georgian
    de = 55 # German
    el = 56 # Greek, Modern (1453–)
    kl = 57 # Kalaallisut, Greenlandic
    gn = 58 # Guarani
    gu = 59 # Gujarati
    ht = 60 # Haitian, Haitian Creole
    ha = 61 # Hausa
    he = 62 # Hebrew
    hz = 63 # Herero
    hi = 64 # Hindi
    ho = 65 # Hiri Motu
    hu = 66 # Hungarian
    io = 68 # Ido
    ig = 69 # Igbo
    id = 70 # Indonesian
    ia = 71 # Interlingua (International Auxiliary Language Association)
    ie = 72 # Interlingue, Occidental
    iu = 73 # Inuktitut
    ik = 74 # Inupiaq
    ga = 75 # Irish
    it = 76 # Italian
    ja = 77 # Japanese
    jv = 78 # Javanese
    kn = 79 # Kannada
    kr = 80 # Kanuri
    ks = 81 # Kashmiri
    kk = 82 # Kazakh
    km = 83 # Central Khmer
    ki = 84 # Kikuyu, Gikuyu
    rw = 85 # Kinyarwanda
    ky = 86 # Kirghiz, Kyrgyz
    kv = 87 # Komi
    kg = 88 # Kongo
    ko = 89 # Korean
    kj = 90 # Kuanyama, Kwanyama
    ku = 91 # Kurdish
    lo = 92 # Lao
    la = 93 # Latin
    lv = 94 # Latvian
    li = 95 # Limburgan, Limburger, Limburgish
    ln = 96 # Lingala
    lt = 97 # Lithuanian
    lu = 98 # Luba-Katanga
    lb = 99 # Luxembourgish, Letzeburgesch
    mk = 100 # Macedonian
    mg = 101 # Malagasy
    ms = 102 # Malay
    ml = 103 # Malayalam
    mt = 104 # Maltese
    gv = 105 # Manx
    mi = 106 # Maori
    mr = 107 # Marathi
    mh = 108 # Marshallese
    mn = 109 # Mongolian
    na = 110 # Nauru
    nv = 111 # Navajo, Navaho
    nd = 112 # North Ndebele
    nr = 113 # South Ndebele
    ng = 114 # Ndonga
    ne = 115 # Nepali
    no = 116 # Norwegian
    nb = 117 # Norwegian Bokmål
    nn = 118 # Norwegian Nynorsk
    ii = 119 # Sichuan Yi, Nuosu
    oc = 120 # Occitan
    oj = 121 # Ojibwa
    om = 123 # Oromo
    os = 124 # Ossetian, Ossetic
    pi = 125 # Pali
    ps = 126 # Pashto, Pushto
    fa = 127 # Persian
    pl = 128 # Polish
    pt = 129 # Portuguese
    pa = 130 # Punjabi, Panjabi
    qu = 131 # Quechua
    ro = 132 # Romanian, Moldavian, Moldovan
    rm = 133 # Romansh
    rn = 134 # Rundi
    ru = 135 # Russian
    se = 136 # Northern Sami
    sm = 137 # Samoan
    sg = 138 # Sango
    sa = 139 # Sanskrit
    sc = 140 # Sardinian
    sr = 141 # Serbian
    sn = 142 # Shona
    sd = 143 # Sindhi
    si = 144 # Sinhala, Sinhalese
    sk = 145 # Slovak
    sl = 146 # Slovenian
    so = 147 # Somali
    st = 148 # Southern Sotho
    es = 149 # Spanish, Castilian
    su = 150 # Sundanese
    sw = 151 # Swahili
    ss = 152 # Swati
    sv = 153 # Swedish
    tl = 154 # Tagalog
    ty = 155 # Tahitian
    tg = 156 # Tajik
    ta = 157 # Tamil
    tt = 158 # Tatar
    te = 159 # Telugu
    th = 160 # Thai
    bo = 161 # Tibetan
    ti = 162 # Tigrinya
    to = 163 # Tonga (Tonga Islands)
    ts = 164 # Tsonga
    tn = 165 # Tswana
    tr = 166 # Turkish
    tk = 167 # Turkmen
    tw = 168 # Twi
    ug = 169 # Uighur, Uyghur
    uk = 170 # Ukrainian
    ur = 171 # Urdu
    uz = 172 # Uzbek
    ve = 173 # Venda
    vi = 174 # Vietnamese
    vo = 175 # Volapük
    wa = 176 # Walloon
    cy = 177 # Welsh
    wo = 178 # Wolof
    xh = 179 # Xhosa
    yi = 180 # Yiddish
    yo = 181 # Yoruba
    za = 182 # Zhuang, Chuang
    zu = 183 # Zulu
